name: Laravel

on:
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - run: ./vendor/bin/phpcs --standard=./phpcs.xml --extensions=php app
    - run: yarn install
    - run: yarn run production
    - name: Configure application
      run: |
        cp .env.example .env
        php artisan cache:clear
        php artisan config:clear
        php artisan key:generate
    - run: ./vendor/bin/phpunit --coverage-text --colors=never